name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ec2-user
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull ***/coursevita_backend:latest
          docker stop coursevita_backend || true
          docker rm coursevita_backend || true
          docker run -d -p 80:8080 --name coursevita_backend ***/coursevita_backend:latest
        port: 22
        debug: true