name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/coursevita_backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/coursevita_backend:latest

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            # Install Docker Compose if not exists
            if ! [ -x "$(command -v docker-compose)" ]; then
              sudo yum install -y libcrypt-compat
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi
            docker-compose --version

            # Navigate to project directory
            cd /home/ec2-user/coursevita_backend

            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKER_USERNAME }}/coursevita_backend:latest

            # Stop and remove the existing container
            docker stop coursevita_backend || true
            docker rm coursevita_backend || true

            # Start the Docker Compose services
            docker-compose down
            docker-compose up -d

            # Run the backend container
            docker run -d -p 80:8080 --name coursevita_backend ${{ secrets.DOCKER_USERNAME }}/coursevita_backend:latest