name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx for multi-platform builds (optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/coursevita_backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/coursevita_backend:latest

      # Step 5: SSH into the EC2 instance and deploy the Docker container
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}  # EC2 instance public IP or DNS
          username: ec2-user              # Default username for Amazon Linux
          key: ${{ secrets.EC2_KEY }}     # Private SSH key for the EC2 instance
          port: 22                        # Default SSH port
          script: |
            # Navigate to project directory
            cd coursevita_backend

            # Pull the latest code
            git pull origin main

            # Install Docker Compose if not exists
            if ! [ -x "$(command -v docker-compose)" ]; then
              sudo yum install -y libcrypt-compat
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi
            docker-compose --version

            # Install missing dependency
            sudo yum install -y libcrypt

            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKER_USERNAME }}/coursevita_backend:latest

            # Stop and remove the existing container
            docker stop coursevita_backend || true
            docker rm coursevita_backend || true

            # Start the Docker Compose services
            docker-compose down
            docker-compose up -d

      # Step 6: Output instance URL
      - name: Output instance URL
        run: |
          echo "Application is deployed and running at: http://${{ secrets.EC2_HOST }}"